### ISSUE TITLE
Registry returned 404 for GET on https://registry.npmjs.org/plugin.google.maps

### ISSUE THREAD

**Issue by musmanzpak** [ionicthemes/ionic-2-google-maps-google-places-geolocation#1]
Facing the following issue while running npm install:

Registry returned 404 for GET on https://registry.npmjs.org/plugin.google.maps

**Comment by kyleschmolze** [comment]
Looks like they moved the NPM package to https://github.com/ionic-team/ionic-native-google-maps/releases. Patched in #3 (waiting for merge)
